# Generated by Django 4.2.7 on 2024-11-19 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "Plant name must contain at least 3 characters"
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                (
                    "room",
                    models.CharField(
                        choices=[
                            ("BEDROOM", "Bedroom"),
                            ("BATHROOM", "Bathroom"),
                            ("LIVINGROOM", "Living room"),
                            ("OFFICE", "Office"),
                            ("HALLWAY", "Hallway"),
                        ],
                        max_length=15,
                    ),
                ),
                ("watered", models.BooleanField()),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_last_updated", models.DateField(auto_now=True)),
            ],
        ),
    ]
