# Generated by Django 4.2.7 on 2024-11-19 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="date_created",
        ),
        migrations.AddField(
            model_name="plant",
            name="date_added",
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
