# Generated by Django 4.2.7 on 2024-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0002_remove_plant_date_created_plant_date_added"),
    ]

    operations = [
        migrations.CreateModel(
            name="Houseplant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="plant",
            old_name="name",
            new_name="nickname",
        ),
    ]
