# Generated by Django 4.2.7 on 2024-11-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0003_houseplant_rename_name_plant_nickname"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Houseplant",
        ),
    ]
