# Generated by Django 4.2.7 on 2024-11-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0004_delete_houseplant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Houseplant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latin_name", models.CharField(max_length=50)),
                ("common_name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=800)),
                ("plant_image", models.URLField()),
                ("light_needed", models.CharField(max_length=15)),
            ],
        ),
    ]
