# Generated by Django 4.2.7 on 2024-11-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0006_alter_houseplant_plant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="common_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plants.houseplant",
            ),
        ),
    ]
