# Generated by Django 4.2.7 on 2024-11-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0007_plant_common_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plant",
            old_name="common_name",
            new_name="plant_type",
        ),
    ]
