# Generated by Django 4.2.7 on 2024-11-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0008_rename_common_name_plant_plant_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="houseplant",
            old_name="plant_image",
            new_name="plant_image_url",
        ),
        migrations.AddField(
            model_name="plant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="plants/"),
        ),
    ]
