# Generated by Django 4.2.7 on 2024-12-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0009_rename_plant_image_houseplant_plant_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="watered",
        ),
        migrations.AddField(
            model_name="plant",
            name="date_last_fertilized",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="date_last_repotted",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="date_last_watered",
            field=models.DateField(auto_now=True),
        ),
    ]
