# Generated by Django 4.2.7 on 2024-12-12 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0010_remove_plant_watered_plant_date_last_fertilized_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="date_added",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="plant",
            name="date_last_fertilized",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="date_last_repotted",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="date_last_watered",
            field=models.DateField(blank=True, null=True),
        ),
    ]
