# Generated by Django 4.2.7 on 2024-12-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0011_alter_plant_date_added_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="fertilize_schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1m", "1 month"),
                    ("2m", "2 month"),
                    ("4m", "4 month"),
                    ("6m", "6 month"),
                    ("1y", "1 year"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="repot_schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1m", "1 month"),
                    ("2m", "2 month"),
                    ("4m", "4 month"),
                    ("6m", "6 month"),
                    ("1y", "1 year"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="water_schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1w", "1 week"),
                    ("2w", "2 weeks"),
                    ("4w", "4 weeks"),
                    ("6w", "6 weeks"),
                ],
                max_length=15,
            ),
        ),
    ]
